import{S as L,i as u,a as S}from"./assets/vendor-e6ae6a6a.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&i(n)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerpolicy&&(r.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?r.credentials="include":e.crossorigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();const b=new L(".photo-container a",{captionsData:"alt",captionDelay:250}),t={searchForm:document.querySelector(".search-form"),photoListEl:document.querySelector(".photo-list"),loader:document.querySelector(".loader"),loaderLoadMore:document.querySelector("loader-load-more"),loadMoreBtn:document.querySelector('[data-action="load-more"]')};let c=1,m=0,d="";const a="is-hidden";t.searchForm.addEventListener("submit",M);async function M(l){l.preventDefault(),t.photoListEl.innerHTML="",t.loader.classList.remove(a),c=1;const o=l.currentTarget;if(d=o.elements.query.value.trim(),!d){t.loader.classList.add(a),u.show({message:"Please enter your request",position:"topRight",color:"yellow"});return}try{const{hits:s,totalHits:i}=await p(d);m=Math.ceil(i/40),h(s,t.photoListEl),s.length>0&&s.length!==i?(t.loadMoreBtn.classList.remove(a),t.loadMoreBtn.addEventListener("click",y)):s.length?t.loadMoreBtn.classList.add(a):(t.loadMoreBtn.classList.add(a),u.error({title:"Error",titleSize:"30",messageSize:"25",message:"Sorry, there are no images matching your search query. Please try again!"}))}catch(s){console.log(s)}finally{t.loader.classList.add(a),o.reset()}}async function p(l,o=1){const s="https://pixabay.com/api",i="41870399-9b44301246ceb98c07efd626a";try{return(await S.get(`${s}/`,{params:{key:i,q:l,image_type:"photo",orientation:"horizontal",safesearch:"true",per_page:40,page:o}})).data}catch{u.error({title:"Error",titleSize:"30",messageSize:"25",message:"Sorry! Try later! Server not working"}),console.error(error.message)}}function h(l){const o=l.map(({webformatURL:s,largeImageURL:i,tags:e,likes:r,views:n,comments:g,downloads:f})=>`<li class="gallery-item">
  <a class="gallery-link" href="${i}">
    <img
      class="gallery-image"
      src="${s}"
      alt="${e}"
    />
  </a><div class="gallery-descr">
   <p>Likes: <br><span>${r}</span></p>
   <p>Views: <br><span>${n}</span></p>
   <p>Comment: <br><span>${g}</span></p>
   <p>Downloads: <br><span>${f}</span></p></div>
</li>`).join("");t.photoListEl.insertAdjacentHTML("beforeend",o),b.refresh()}async function y(){c+=1,t.loaderLoadMore.classList.remove(a),t.loadMoreBtn.classList.add(a);const l=document.querySelector(".gallery-item").getBoundingClientRect();try{const{hits:o}=await p(d,c);h(o,t.photoListEl)}catch(o){console.log(o)}finally{window.scrollBy({top:l.height*2,left:0,behavior:"smooth"}),t.loaderLoadMore.classList.add(a),t.loadMoreBtn.classList.remove(a),c===m&&(t.loadMoreBtn.classList.add(a),t.loadMoreBtn.removeEventListener("click",y),u.show({title:"Hey",titleSize:"30",messageSize:"25",color:"blue",position:"topRight",message:"We're sorry, but you've reached the end of search results."}))}}
//# sourceMappingURL=commonHelpers.js.map
